name: "Pull Request Content Checker"
description: "GitHub Container Action built with Python, validates that a pull request body was modified from the original template and is not empty"
author: "Mikael Andersson"
inputs:
  pull_request_template_path:
    description: "Path to the pull request template used by the repository"
    default: ".github/pull_request_template.md"
  max_pull_request_description_match:
    description: "Maximum value of percentage match (0-1) between body and template before the action fails"
    default: "0.7"
  github_token:
    description: "GitHub Token used for retrieving pull request details in API requests"
outputs:
  pull_request_body_match:
    description: "Output to indicate the similarity with the pull request template (score between 0-1)"
runs:
  using: "docker"
  image: "Dockerfile"
