# Controls when the workflow will run
name: Commitsar
on:
    pull_request:
      branches: [ "master" ]

permissions: read-all

jobs:
  commitsar: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Commitsar Action
        uses: aevea/commitsar@v0.20.2
        with:
          config: ${{ github.workspace }}/.commitsar.yml
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}