name: Lint
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        run: |
          pip install flake8
          flake8 main.py
